# -*- coding: utf-8 -*-
"""OIBSIP_TASKNO3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jYW86cnOd5N8Phz2YlPvFcHU-Zb2uJzi
"""

import random
def generatePassword(n):
    characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ123456789!@#$%^&*()"
    chosenLetter = random.sample(characters, n)
    password = "".join(chosenLetter)
    return password
if __name__ == "__main__":
    n = int(input("Enter the length of the password: "))
    password = generatePassword(n)
    print("A randomly selected password is:", password)